shared: &shared
  adapter: postgresql
  encoding: utf8
  username: <%= ENV["USER"] || "postgres" %>

development:
  <<: *shared
  database: pixie_development

test:
  <<: *shared
  database: pixie_test
  min_messages: WARNING

production:
  <<: *shared
  database: pixie_production
